pub mod overrides;

use std::collections::HashMap;
use std::fmt::Write;

use anyhow::{Context, Result};
use chrono::{DateTime, Datelike as _, FixedOffset, NaiveDateTime, Timelike as _};
use lazy_static::lazy_static;
use memo_map::MemoMap;
use regex::Regex;
use serde::{Deserialize, Serialize};

use overrides::*;

#[derive(Serialize, Deserialize, Debug)]
pub struct ChannelVersions {
    pub dev: ChannelVersion,
    pub preview: ChannelVersion,
    pub stable: ChannelVersion,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub changelogs: Option<ChannelChangelogs>,
}

impl std::fmt::Display for ChannelVersions {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "dev: {:?}; preview: {:?}; stable: {:?}",
            self.dev, self.preview, self.stable
        )
    }
}

lazy_static! {
    static ref VERSION_RE: Regex = Regex::new(r"v(\d+)\.(.+)\.(.+)_(\d+)").unwrap();

    // Every release tag this fork's pipeline actually publishes, in one pattern:
    //   * `v0.1.0`, `v0.1.1`          -- hand-cut semver-ish releases;
    //   * `v2026.08.14.1-beta`        -- date tag with a prerelease suffix
    //                                   (published with `make_latest:false`);
    //   * `v0.2026.08.21.1430`        -- generated by `phosphor_release.yml`'s
    //                                   workflow_dispatch branch,
    //                                   `TAG="v0.$(date +%Y.%m.%d.%H%M)"`.
    //   * `v2026.05.10.preview`       -- the channel-labelled shape
    //                                   `app/src/autoupdate/mod.rs` documents
    //                                   for `GIT_RELEASE_TAG`; the label may be
    //                                   attached with `.` or with `-`.
    // The `v` is optional because the two sides of every comparison disagree
    // about it: `ChannelState::app_version()` keeps the prefix, while
    // `github::GithubRelease::version()` trims it.
    //
    // Deliberately anchored, unlike VERSION_RE: this is also the gate
    // `warp_tui::autoupdate::parse_safe_version_component` leans on to keep a
    // server-supplied string from escaping `versions/`, so `preview-1`, `A`,
    // `trailing.` and `v1..dev` must all still fail to parse.
    static ref RELEASE_TAG_RE: Regex =
        Regex::new(r"^[vV]?(\d{1,8}(?:\.\d{1,8}){1,7})(?:[.-]([0-9A-Za-z][0-9A-Za-z.-]*))?$")
            .unwrap();

    // Cached mapping of version strings to semantic versions.
    static ref PARSED_VERSIONS_CACHE: MemoMap<String, ParsedVersion> = Default::default();
}

/// A version tag reduced to something orderable.
///
/// This used to be a fixed `(major, date, patch)` triple, which could only
/// represent the official `vM.YYYY.MM.DD.HH.MM.<channel>_NN` shape. None of the
/// tags this fork publishes fit that triple -- `v0.1.1` has no date at all --
/// so every one of them failed to parse, and every caller that swallows the
/// resulting `Err` (see `autoupdate::should_update`) silently lost its guard.
/// The representation is therefore a plain list of numeric components plus an
/// optional prerelease identifier, which all the shapes above map onto.
#[derive(Debug, PartialEq, Eq, Serialize, Deserialize, Clone)]
pub struct ParsedVersion {
    /// Numeric release components, most significant first. Compared
    /// element-wise, zero-padding the shorter of the two.
    components: Vec<usize>,
    /// Trailing non-numeric label -- `beta` in `v2026.08.14.1-beta`, `preview`
    /// in `v2026.05.10.preview`. Compared only after every numeric component
    /// ties, and an unlabelled tag outranks a labelled one, as in semver.
    prerelease: Option<String>,
}

impl ParsedVersion {
    fn new(mut components: Vec<usize>, prerelease: Option<String>) -> Self {
        // Trailing zeros carry no information (`v0.1.0` is `v0.1`). Dropping
        // them keeps the derived `PartialEq` consistent with the zero-padding
        // `Ord` below -- without it `[0, 1]` and `[0, 1, 0]` would compare
        // `Equal` yet be unequal.
        while components.len() > 1 && components.last() == Some(&0) {
            components.pop();
        }
        Self {
            components,
            prerelease,
        }
    }
}

impl TryFrom<&str> for ParsedVersion {
    type Error = anyhow::Error;

    fn try_from(value: &str) -> Result<Self> {
        PARSED_VERSIONS_CACHE
            .get_or_try_insert(value, || {
                if let Some(parsed) = parse_official(value).or_else(|| parse_release_tag(value)) {
                    Ok(parsed)
                } else {
                    Err(anyhow::anyhow!("Can't parse string into Version"))
                        .context(format!("invalid version: {value}"))
                }
            })
            .cloned()
    }
}

fn parse_official(value: &str) -> Option<ParsedVersion> {
    let captures = VERSION_RE.captures(value.trim())?;
    let date_str = captures.get(2)?.as_str();
    // Still parsed as a date rather than as three more numbers, so that an
    // impossible date (`.2023.13.45.`) is rejected exactly as before.
    let date = NaiveDateTime::parse_from_str(date_str, "%Y.%m.%d.%H.%M").ok()?;
    let major: usize = captures.get(1)?.as_str().parse().ok()?;
    let patch: usize = captures.get(4)?.as_str().parse().ok()?;
    // major.year.month.day.hour.minute.patch -- element-wise comparison over
    // this list reproduces the old `(major, date, patch)` tuple ordering
    // exactly for official-vs-official comparisons.
    Some(ParsedVersion::new(
        vec![
            major,
            date.year().max(0) as usize,
            date.month() as usize,
            date.day() as usize,
            date.hour() as usize,
            date.minute() as usize,
            patch,
        ],
        None,
    ))
}

/// Parses the tag shapes this fork's release pipeline emits.
///
/// Ordering note: a bare date tag (`v2026.08.14.1`) gets a synthetic leading
/// `0` so that it lands on the same `major.YYYY.MM.DD...` axis as the
/// dispatch-generated `v0.2026.08.21.1430`. That also preserves the older
/// invariant that an OSS tag never outranks an official `vM....` tag for
/// `M >= 1`.
///
/// A consequence worth stating plainly: mixing the two schemes this repo has
/// used means a date tag (`2026....`) always outranks a semver-ish one
/// (`0.1.1`), because 2026 > 1 in the second component. That is the behaviour
/// the downgrade guard needs -- a user on `v2026.08.14.1-beta` must not be
/// walked back onto `v0.1.1`, which `/releases/latest` reports because betas
/// are published with `make_latest:false`. It also means such a user is not
/// offered later `v0.1.x` releases; moving them forward needs
/// release-channel awareness, not a numeric comparison.
fn parse_release_tag(value: &str) -> Option<ParsedVersion> {
    let captures = RELEASE_TAG_RE.captures(value.trim())?;
    let mut components: Vec<usize> = captures
        .get(1)?
        .as_str()
        .split('.')
        .map(|segment| segment.parse::<usize>().ok())
        .collect::<Option<Vec<_>>>()?;
    if components.first().is_some_and(|first| *first >= 1000) {
        components.insert(0, 0);
    }
    let prerelease = captures.get(2).map(|m| m.as_str().to_ascii_lowercase());
    Some(ParsedVersion::new(components, prerelease))
}

impl Ord for ParsedVersion {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        let len = self.components.len().max(other.components.len());
        for i in 0..len {
            let ours = self.components.get(i).copied().unwrap_or(0);
            let theirs = other.components.get(i).copied().unwrap_or(0);
            match ours.cmp(&theirs) {
                std::cmp::Ordering::Equal => {}
                unequal => return unequal,
            }
        }
        // Semver's rule: `1.0.0-beta` precedes `1.0.0`.
        match (&self.prerelease, &other.prerelease) {
            (None, None) => std::cmp::Ordering::Equal,
            (None, Some(_)) => std::cmp::Ordering::Greater,
            (Some(_), None) => std::cmp::Ordering::Less,
            (Some(ours), Some(theirs)) => ours.cmp(theirs),
        }
    }
}

impl PartialOrd for ParsedVersion {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
pub struct ChannelVersion {
    #[serde(flatten)]
    version_info: VersionInfo,
    /// Any overrides which should be applied for this channel.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    overrides: Vec<VersionOverride>,
}

impl ChannelVersion {
    pub fn new(version_info: VersionInfo) -> Self {
        Self {
            version_info,
            overrides: vec![],
        }
    }

    /// Returns the version information, with any applicable overrides applied
    /// based on the current execution environment.
    pub fn version_info(&self) -> VersionInfo {
        let context = overrides::Context::from_env();
        self.version_info
            .with_overrides_applied(&self.overrides, &context)
    }

    /// Returns the version information, with any applicable overrides applied
    /// based on the provided context.
    pub fn version_info_for_execution_context(&self, context: &overrides::Context) -> VersionInfo {
        self.version_info
            .with_overrides_applied(&self.overrides, context)
    }
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
pub struct VersionInfo {
    pub version: String,
    /// The version to download for new users from the download page. This is not used on the client
    /// other than in the `apply_overrides` binary used from the `channel-versions` repo.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version_for_new_users: Option<String>,
    /// The time by which the client needs to be updated, after which
    /// the user sees a warning banner.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub update_by: Option<DateTime<FixedOffset>>,
    /// If specified, this field indicates the oldest version of the client that is still
    /// supported. Any version before this version is not supported and the user should update.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub soft_cutoff: Option<String>,
    /// If specified, this field indicates the latest client version that has a prominent update.
    /// Versions before `prominent_update` should display the prominent update UI.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_prominent_update: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub is_rollback: Option<bool>,
    /// The version to use for CLI downloads, falling back to `version` if not set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cli_version: Option<String>,
    /// The version to use for TUI downloads, falling back to `version` if not set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tui_version: Option<String>,
}

impl VersionInfo {
    pub fn new(version: String) -> Self {
        Self {
            version,
            update_by: None,
            soft_cutoff: None,
            last_prominent_update: None,
            version_for_new_users: None,
            is_rollback: None,
            cli_version: None,
            tui_version: None,
        }
    }

    /// Returns the CLI version, falling back to the app version if not set.
    pub fn cli_version(&self) -> &str {
        self.cli_version.as_deref().unwrap_or(&self.version)
    }

    /// Returns the TUI version, falling back to the app version if not set.
    pub fn tui_version(&self) -> &str {
        self.tui_version.as_deref().unwrap_or(&self.version)
    }
}

#[derive(Serialize, Deserialize, Debug)]
pub struct ChannelChangelogs {
    // Maps of changelogs by version
    pub dev: HashMap<String, Changelog>,
    pub preview: HashMap<String, Changelog>,
    pub stable: HashMap<String, Changelog>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
pub struct Changelog {
    pub date: DateTime<FixedOffset>,
    pub sections: Vec<Section>,
    #[serde(default = "default_markdown_sections")]
    pub markdown_sections: Vec<MarkdownSection>,
    #[serde(default)]
    pub image_url: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub oz_updates: Vec<String>,
}

// Default value for when the changelog JSON doesn't have the markdown_sections field
fn default_markdown_sections() -> Vec<MarkdownSection> {
    vec![
        MarkdownSection {
            title: "New features".to_string(),
            markdown: "".to_string(),
        },
        MarkdownSection {
            title: "Improvements".to_string(),
            markdown: "".to_string(),
        },
        MarkdownSection {
            title: "Coming soon".to_string(),
            markdown: "".to_string(),
        },
    ]
}

impl std::fmt::Display for Changelog {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            self.sections
                .iter()
                .fold(String::new(), |mut output, item| {
                    let _ = write!(output, "{item}\n\n");
                    output
                })
        )
    }
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
pub struct Section {
    pub title: String,
    pub items: Vec<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
pub struct MarkdownSection {
    pub title: String,
    pub markdown: String,
}

impl std::fmt::Display for Section {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}:\n{}",
            self.title,
            self.items.iter().fold(String::new(), |mut output, item| {
                let _ = writeln!(output, "- {item}");
                output
            })
        )
    }
}

#[cfg(test)]
#[path = "channel_versions_tests.rs"]
mod tests;
