pub mod overrides;

use std::collections::HashMap;
use std::fmt::Write;

use anyhow::{Context, Result};
use chrono::{DateTime, Datelike as _, FixedOffset, NaiveDateTime, Timelike as _};
use lazy_static::lazy_static;
use memo_map::MemoMap;
use regex::Regex;
use serde::{Deserialize, Serialize};

use overrides::*;

#[derive(Serialize, Deserialize, Debug)]
pub struct ChannelVersions {
    pub dev: ChannelVersion,
    pub preview: ChannelVersion,
    pub stable: ChannelVersion,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub changelogs: Option<ChannelChangelogs>,
}

impl std::fmt::Display for ChannelVersions {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "dev: {:?}; preview: {:?}; stable: {:?}",
            self.dev, self.preview, self.stable
        )
    }
}

lazy_static! {
    static ref VERSION_RE: Regex = Regex::new(r"v(\d+)\.(.+)\.(.+)_(\d+)").unwrap();

    // Every release tag this fork's pipeline actually publishes, in one pattern:
    //   * `v0.1.0`, `v0.1.1`          -- hand-cut semver-ish releases;
    //   * `v2026.08.14.1-beta`        -- date tag with a prerelease suffix
    //                                   (published with `make_latest:false`);
    //   * `v0.2026.08.21.1430`        -- generated by `phosphor_release.yml`'s
    //                                   workflow_dispatch branch,
    //                                   `TAG="v0.$(date +%Y.%m.%d.%H%M)"`.
    //   * `v2026.05.10.preview`       -- the channel-labelled shape
    //                                   `app/src/autoupdate/mod.rs` documents
    //                                   for `GIT_RELEASE_TAG`; the label may be
    //                                   attached with `.` or with `-`.
    // The `v` is optional because the two sides of every comparison disagree
    // about it: `ChannelState::app_version()` keeps the prefix, while
    // `github::GithubRelease::version()` trims it.
    //
    // The label must begin with a letter. A purely numeric suffix cannot be
    // told apart from one more numeric component, and because the numeric group
    // can hand segments back to the suffix, permitting one made the anchors
    // decorative: with `[0-9A-Za-z][0-9A-Za-z.-]*` the group backtracked, so
    // `v0.1.1-` matched as `0.1` + `1-`, `v1.2.3.` as `1.2` + `3.`, and
    // `v1.2.3.4.5.6.7.8.9` as eight components plus a "label" of `9` -- a
    // numeric component silently reclassified as a prerelease. Requiring a
    // leading `[A-Za-z]` removes the ambiguity; the cost is semver's
    // bare-numeric prereleases (`v1.2.3-1`), which nothing here publishes.
    //
    // Anchored, unlike VERSION_RE, so a version-shaped substring of a longer
    // string is not accepted. It is *not*, however, what stops a
    // server-supplied string escaping `versions/`:
    // `warp_tui::autoupdate::parse_safe_version_component` is handed
    // `../v0.2026.07.28.12.00.dev_00`, and `parse_official`'s unanchored
    // VERSION_RE -- tried first -- parses it happily. The separator check in
    // that function is the traversal gate; its own test says as much.
    static ref RELEASE_TAG_RE: Regex = Regex::new(
        r"^[vV]?(\d{1,8}(?:\.\d{1,8}){1,7})(?:[.-]([A-Za-z][0-9A-Za-z-]*(?:\.[0-9A-Za-z-]+)*))?$"
    )
    .unwrap();

    // Cached mapping of version strings to semantic versions.
    static ref PARSED_VERSIONS_CACHE: MemoMap<String, ParsedVersion> = Default::default();
}

/// A leading component this large is a year, not a major version: it is what
/// marks the bare date tags (`v2026.08.14.1`) that get the synthetic `0` major.
const MIN_DATE_TAG_YEAR: usize = 1000;

/// The build-counter slot given to a `workflow_dispatch` build, which has no
/// counter of its own. Zero puts it below the first numbered release of the
/// same date and above that date's unnumbered tag.
const DISPATCH_BUILD_COUNTER: usize = 0;

/// A version tag reduced to something orderable.
///
/// This used to be a fixed `(major, date, patch)` triple, which could only
/// represent the official `vM.YYYY.MM.DD.HH.MM.<channel>_NN` shape. None of the
/// tags this fork publishes fit that triple -- `v0.1.1` has no date at all --
/// so every one of them failed to parse, and every caller that swallows the
/// resulting `Err` (see `autoupdate::should_update`) silently lost its guard.
/// The representation is therefore a plain list of numeric components plus an
/// optional prerelease identifier, which all the shapes above map onto.
#[derive(Debug, PartialEq, Eq, Serialize, Clone)]
pub struct ParsedVersion {
    /// Numeric release components, most significant first. Compared
    /// element-wise, zero-padding the shorter of the two.
    components: Vec<usize>,
    /// Trailing non-numeric label -- `beta` in `v2026.08.14.1-beta`, `preview`
    /// in `v2026.05.10.preview`. Compared only after every numeric component
    /// ties; an unlabelled tag outranks a labelled one, and two labels are
    /// compared identifier by identifier, numerically where both are numbers,
    /// per semver 11.4 -- so `beta.2` precedes `beta.10`. Case is preserved:
    /// `-RC1` and `-rc1` are different tags and must not compare `Equal`.
    prerelease: Option<String>,
}

/// Deserialised by hand rather than derived, because the fields are private for
/// a reason: `new()` maintains an invariant -- no trailing zero components --
/// that the zero-padding [`Ord`] and the derived [`PartialEq`] both rely on, and
/// a derived `Deserialize` would build the struct behind `new()`'s back.
/// Nothing deserialises a `ParsedVersion` today; this keeps the door from being
/// a way to mint a value whose `a == b` disagrees with `a.cmp(&b)`.
impl<'de> Deserialize<'de> for ParsedVersion {
    fn deserialize<D>(deserializer: D) -> std::result::Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        #[derive(Deserialize)]
        struct Wire {
            components: Vec<usize>,
            #[serde(default)]
            prerelease: Option<String>,
        }

        let wire = Wire::deserialize(deserializer)?;
        Ok(ParsedVersion::new(wire.components, wire.prerelease))
    }
}

impl ParsedVersion {
    fn new(mut components: Vec<usize>, prerelease: Option<String>) -> Self {
        // Trailing zeros carry no information (`v0.1.0` is `v0.1`). Dropping
        // them keeps the derived `PartialEq` consistent with the zero-padding
        // `Ord` below -- without it `[0, 1]` and `[0, 1, 0]` would compare
        // `Equal` yet be unequal.
        //
        // The loop runs down to the empty vector on purpose. A `len() > 1`
        // guard reads like harmless defensiveness and is not: it stops at
        // `[0]`, so `[]` and `[0]` -- both of which `Deserialize` will accept,
        // and which `Ord` zero-pads into `Equal` -- stay unequal under
        // `PartialEq`. That is precisely the disagreement this canonicalisation
        // exists to prevent, left standing in the one case the hand-written
        // `Deserialize` was written to close. Nothing downstream needs a
        // non-empty list: `Ord` reads components with `get(i).unwrap_or(0)`,
        // and every parser calls `new()` with at least two segments anyway, so
        // an empty list can only arise from a deserialised all-zero version,
        // which is exactly the value that should canonicalise to it.
        while components.last() == Some(&0) {
            components.pop();
        }
        Self {
            components,
            prerelease,
        }
    }
}

impl TryFrom<&str> for ParsedVersion {
    type Error = anyhow::Error;

    fn try_from(value: &str) -> Result<Self> {
        PARSED_VERSIONS_CACHE
            .get_or_try_insert(value, || {
                if let Some(parsed) = parse_official(value).or_else(|| parse_release_tag(value)) {
                    Ok(parsed)
                } else {
                    Err(anyhow::anyhow!("Can't parse string into Version"))
                        .context(format!("invalid version: {value}"))
                }
            })
            .cloned()
    }
}

fn parse_official(value: &str) -> Option<ParsedVersion> {
    let captures = VERSION_RE.captures(value.trim())?;
    let date_str = captures.get(2)?.as_str();
    // Still parsed as a date rather than as three more numbers, so that an
    // impossible date (`.2023.13.45.`) is rejected exactly as before.
    let date = NaiveDateTime::parse_from_str(date_str, "%Y.%m.%d.%H.%M").ok()?;
    let major: usize = captures.get(1)?.as_str().parse().ok()?;
    let patch: usize = captures.get(4)?.as_str().parse().ok()?;
    // major.year.month.day.hour.minute.patch -- element-wise comparison over
    // this list reproduces the old `(major, date, patch)` tuple ordering
    // exactly for official-vs-official comparisons.
    Some(ParsedVersion::new(
        vec![
            major,
            date.year().max(0) as usize,
            date.month() as usize,
            date.day() as usize,
            date.hour() as usize,
            date.minute() as usize,
            patch,
        ],
        None,
    ))
}

/// Parses the tag shapes this fork's release pipeline emits.
///
/// Two of those shapes put different quantities in the same slot, and they have
/// to be pulled apart here or they order wrongly:
///
///   * a tag-triggered date release, `vYYYY.MM.DD.N`, whose fourth segment is a
///     *build counter* -- the published `v2026.08.14.1-beta` is the example;
///   * a `workflow_dispatch` build, tagged `v0.$(date +%Y.%m.%d.%H%M)` by
///     `.github/workflows/phosphor_release.yml`, whose fifth segment is an
///     `HHMM` *clock reading*.
///
/// A bare date tag gets a synthetic leading `0` so that it lands on the same
/// `major.YYYY.MM.DD...` axis as the dispatch tag, which also preserves the
/// older invariant that an OSS tag never outranks an official `vM....` tag for
/// `M >= 1`. Stopping there fused the counter with the clock: dispatch
/// `v0.2026.08.21.0930` became `[0, 2026, 8, 21, 930]` and outranked the same
/// day's real release `v2026.08.21.1` -> `[0, 2026, 8, 21, 1]`, so everyone on
/// a dispatch build would rank the release below what they were running and
/// never update -- the exact failure the downgrade guard exists to prevent.
///
/// So the clock reading is expanded onto its own `hour`/`minute` axis *below*
/// the counter, with the counter left at [`DISPATCH_BUILD_COUNTER`]: an ad-hoc
/// build of a date is treated as a pre-release of that date, superseded by the
/// first numbered release of it and ordered among its own kind by time of day.
/// [`dispatch_clock_reading`] is how the two shapes are told apart.
///
/// A consequence worth stating plainly: mixing the two schemes this repo has
/// used means a date tag (`2026....`) always outranks a semver-ish one
/// (`0.1.1`), because 2026 > 1 in the second component. That is the behaviour
/// the downgrade guard needs -- a user on `v2026.08.14.1-beta` must not be
/// walked back onto `v0.1.1`, which `/releases/latest` reports because betas
/// are published with `make_latest:false`. It also means such a user is not
/// offered later `v0.1.x` releases; moving them forward needs
/// release-channel awareness, not a numeric comparison.
fn parse_release_tag(value: &str) -> Option<ParsedVersion> {
    let captures = RELEASE_TAG_RE.captures(value.trim())?;
    let segments: Vec<&str> = captures.get(1)?.as_str().split('.').collect();
    let mut components: Vec<usize> = segments
        .iter()
        .map(|segment| segment.parse::<usize>().ok())
        .collect::<Option<Vec<_>>>()?;
    let clock = dispatch_clock_reading(&segments, &components);
    if components
        .first()
        .is_some_and(|first| *first >= MIN_DATE_TAG_YEAR)
    {
        components.insert(0, 0);
    } else if let Some((hour, minute)) = clock {
        components.truncate(4);
        components.extend_from_slice(&[DISPATCH_BUILD_COUNTER, hour, minute]);
    }
    // Not lower-cased: `-RC1` and `-rc1` are two different tags, and folding
    // them together would make them compare `Equal`.
    let prerelease = captures.get(2).map(|m| m.as_str().to_owned());
    Some(ParsedVersion::new(components, prerelease))
}

/// Recognises the `workflow_dispatch` tag `v0.$(date +%Y.%m.%d.%H%M)` by its
/// shape -- a `0` major, a year, a month, a day, and a *four digit* `HHMM` --
/// returning the `(hour, minute)` it encodes.
///
/// The digit count is the discriminator that matters: `date +%H%M` zero-pads,
/// so 09:30 is written `0930`, which is not how anyone writes a build counter.
/// Without it, a hand-cut `v0.2026.08.21.3` would be read as 00:03 rather than
/// as counter 3.
fn dispatch_clock_reading(segments: &[&str], components: &[usize]) -> Option<(usize, usize)> {
    if components.len() != 5 || components[0] != 0 || components[1] < MIN_DATE_TAG_YEAR {
        return None;
    }
    if segments.get(4)?.len() != 4 {
        return None;
    }
    let (hour, minute) = (components[4] / 100, components[4] % 100);
    (hour < 24 && minute < 60).then_some((hour, minute))
}

impl Ord for ParsedVersion {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        let len = self.components.len().max(other.components.len());
        for i in 0..len {
            let ours = self.components.get(i).copied().unwrap_or(0);
            let theirs = other.components.get(i).copied().unwrap_or(0);
            match ours.cmp(&theirs) {
                std::cmp::Ordering::Equal => {}
                unequal => return unequal,
            }
        }
        // Semver's rule: `1.0.0-beta` precedes `1.0.0`.
        match (&self.prerelease, &other.prerelease) {
            (None, None) => std::cmp::Ordering::Equal,
            (None, Some(_)) => std::cmp::Ordering::Greater,
            (Some(_), None) => std::cmp::Ordering::Less,
            (Some(ours), Some(theirs)) => compare_prerelease(ours, theirs),
        }
    }
}

impl PartialOrd for ParsedVersion {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

/// Semver 11.4 precedence for two prerelease labels: split on `.` and compare
/// identifier by identifier; if one label runs out first with everything so far
/// equal, the longer one wins.
///
/// A plain `str::cmp` was wrong for the shape this repo documents
/// (`v2026.08.01-beta.1`, in `.github/workflows/phosphor_release.yml`): it put
/// `beta.10` *below* `beta.2`, so the tenth beta of a date read as a downgrade
/// from the second.
fn compare_prerelease(ours: &str, theirs: &str) -> std::cmp::Ordering {
    let mut ours = ours.split('.');
    let mut theirs = theirs.split('.');
    loop {
        match (ours.next(), theirs.next()) {
            (None, None) => return std::cmp::Ordering::Equal,
            (None, Some(_)) => return std::cmp::Ordering::Less,
            (Some(_), None) => return std::cmp::Ordering::Greater,
            (Some(ours), Some(theirs)) => match compare_identifier(ours, theirs) {
                std::cmp::Ordering::Equal => {}
                unequal => return unequal,
            },
        }
    }
}

/// Compares one prerelease identifier: numerically when both are numbers,
/// otherwise by ASCII, and a numeric identifier always ranks below an
/// alphanumeric one.
fn compare_identifier(ours: &str, theirs: &str) -> std::cmp::Ordering {
    match (numeric_identifier(ours), numeric_identifier(theirs)) {
        (Some(ours), Some(theirs)) => ours.cmp(&theirs),
        (Some(_), None) => std::cmp::Ordering::Less,
        (None, Some(_)) => std::cmp::Ordering::Greater,
        (None, None) => ours.cmp(theirs),
    }
}

/// The numeric value of an identifier, if it is one in the canonical semver
/// sense: all ASCII digits, and no leading zero.
///
/// The leading-zero exclusion is what keeps [`Ord`] consistent with the derived
/// [`PartialEq`]. Treating `01` as the number 1 would make `beta.01` and
/// `beta.1` compare `Equal` while remaining unequal values; compared as text
/// they are simply `Less`, and no two distinct labels can now tie.
fn numeric_identifier(identifier: &str) -> Option<u64> {
    if identifier.len() > 1 && identifier.starts_with('0') {
        return None;
    }
    if !identifier.bytes().all(|byte| byte.is_ascii_digit()) {
        return None;
    }
    identifier.parse::<u64>().ok()
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
pub struct ChannelVersion {
    #[serde(flatten)]
    version_info: VersionInfo,
    /// Any overrides which should be applied for this channel.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    overrides: Vec<VersionOverride>,
}

impl ChannelVersion {
    pub fn new(version_info: VersionInfo) -> Self {
        Self {
            version_info,
            overrides: vec![],
        }
    }

    /// Returns the version information, with any applicable overrides applied
    /// based on the current execution environment.
    pub fn version_info(&self) -> VersionInfo {
        let context = overrides::Context::from_env();
        self.version_info
            .with_overrides_applied(&self.overrides, &context)
    }

    /// Returns the version information, with any applicable overrides applied
    /// based on the provided context.
    pub fn version_info_for_execution_context(&self, context: &overrides::Context) -> VersionInfo {
        self.version_info
            .with_overrides_applied(&self.overrides, context)
    }
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
pub struct VersionInfo {
    pub version: String,
    /// The version to download for new users from the download page. This is not used on the client
    /// other than in the `apply_overrides` binary used from the `channel-versions` repo.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version_for_new_users: Option<String>,
    /// The time by which the client needs to be updated, after which
    /// the user sees a warning banner.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub update_by: Option<DateTime<FixedOffset>>,
    /// If specified, this field indicates the oldest version of the client that is still
    /// supported. Any version before this version is not supported and the user should update.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub soft_cutoff: Option<String>,
    /// If specified, this field indicates the latest client version that has a prominent update.
    /// Versions before `prominent_update` should display the prominent update UI.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_prominent_update: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub is_rollback: Option<bool>,
    /// The version to use for CLI downloads, falling back to `version` if not set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cli_version: Option<String>,
    /// The version to use for TUI downloads, falling back to `version` if not set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tui_version: Option<String>,
}

impl VersionInfo {
    pub fn new(version: String) -> Self {
        Self {
            version,
            update_by: None,
            soft_cutoff: None,
            last_prominent_update: None,
            version_for_new_users: None,
            is_rollback: None,
            cli_version: None,
            tui_version: None,
        }
    }

    /// Returns the CLI version, falling back to the app version if not set.
    pub fn cli_version(&self) -> &str {
        self.cli_version.as_deref().unwrap_or(&self.version)
    }

    /// Returns the TUI version, falling back to the app version if not set.
    pub fn tui_version(&self) -> &str {
        self.tui_version.as_deref().unwrap_or(&self.version)
    }
}

#[derive(Serialize, Deserialize, Debug)]
pub struct ChannelChangelogs {
    // Maps of changelogs by version
    pub dev: HashMap<String, Changelog>,
    pub preview: HashMap<String, Changelog>,
    pub stable: HashMap<String, Changelog>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
pub struct Changelog {
    pub date: DateTime<FixedOffset>,
    pub sections: Vec<Section>,
    #[serde(default = "default_markdown_sections")]
    pub markdown_sections: Vec<MarkdownSection>,
    #[serde(default)]
    pub image_url: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub oz_updates: Vec<String>,
}

// Default value for when the changelog JSON doesn't have the markdown_sections field
fn default_markdown_sections() -> Vec<MarkdownSection> {
    vec![
        MarkdownSection {
            title: "New features".to_string(),
            markdown: "".to_string(),
        },
        MarkdownSection {
            title: "Improvements".to_string(),
            markdown: "".to_string(),
        },
        MarkdownSection {
            title: "Coming soon".to_string(),
            markdown: "".to_string(),
        },
    ]
}

impl std::fmt::Display for Changelog {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            self.sections
                .iter()
                .fold(String::new(), |mut output, item| {
                    let _ = write!(output, "{item}\n\n");
                    output
                })
        )
    }
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
pub struct Section {
    pub title: String,
    pub items: Vec<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
pub struct MarkdownSection {
    pub title: String,
    pub markdown: String,
}

impl std::fmt::Display for Section {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}:\n{}",
            self.title,
            self.items.iter().fold(String::new(), |mut output, item| {
                let _ = writeln!(output, "- {item}");
                output
            })
        )
    }
}

#[cfg(test)]
#[path = "channel_versions_tests.rs"]
mod tests;
