//! Issue #116: integration tests for `collect_user_rules`.
//!
//! Uses the `warpui::App::test` harness to actually stuff `AIFact::Memory` into
//! `ObjectStoreModel`, verifying the collection logic (filtering trashed / sorting /
//! no-name, etc.). The harness initialization reuses the boilerplate from
//! `data_source_tests.rs`.

use settings::manager::SettingsManager;
use warpui::{App, SingletonEntity};

use super::{collect_user_rules, ServerConversationToken};
use crate::ai::agent::ServerOutputId;
use crate::ai::facts::{AIFact, AIFactObject, AIFactObjectModel, AIMemory};
use crate::auth::AuthStateProvider;
use crate::cloud_object::model::persistence::ObjectStoreModel;
use crate::cloud_object::model::view::ObjectStoreViewModel;
use crate::cloud_object::update_manager::UpdateManager;
use crate::cloud_object::{StoredObjectMetadata, StoredObjectPermissions};
use crate::server_time::ServerTimestamp;
use crate::notebooks::manager::NotebookManager;
use crate::server::ids::SyncId;
use crate::settings::AISettings;
use crate::system::SystemStats;
use crate::workspaces::user_profiles::UserProfiles;
use crate::workspaces::user_workspaces::UserWorkspaces;
use crate::NetworkStatus;

fn initialize_app(app: &mut App) {
    app.add_singleton_model(|_| NetworkStatus::new());
    app.add_singleton_model(|_| SystemStats::new());
    app.add_singleton_model(|ctx| UserWorkspaces::mock(vec![], ctx));
    app.add_singleton_model(ObjectStoreModel::mock);
    app.add_singleton_model(|ctx| UpdateManager::new(None, ctx));
    app.add_singleton_model(|_| UserProfiles::new(Vec::new()));
    app.add_singleton_model(ObjectStoreViewModel::new);
    app.add_singleton_model(NotebookManager::mock);
    app.add_singleton_model(|_| SettingsManager::default());
    app.add_singleton_model(|_| AuthStateProvider::new_for_test());
    app.update(crate::settings::init_and_register_user_preferences);
    app.update(AISettings::register_and_subscribe_to_events);
}

fn make_rule(id: i64, name: Option<&str>, content: &str, trashed: bool) -> AIFactObject {
    let sync_id = SyncId::ServerId(id.into());
    let mut metadata = StoredObjectMetadata::mock();
    if trashed {
        metadata.trashed_ts = Some(ServerTimestamp::from_unix_timestamp_micros(10).unwrap());
    }
    AIFactObject::new(
        sync_id,
        AIFactObjectModel::new(AIFact::Memory(AIMemory {
            name: name.map(str::to_string),
            content: content.to_string(),
            is_autogenerated: false,
            suggested_logging_id: None,
        })),
        metadata,
        StoredObjectPermissions::mock_personal(),
    )
}

#[test]
fn collect_user_rules_returns_empty_when_store_is_empty() {
    App::test((), |mut app| async move {
        initialize_app(&mut app);
        let rules = app.read(|app| collect_user_rules(ObjectStoreModel::as_ref(app)));
        assert!(rules.is_empty(), "empty store should return empty Vec, got: {rules:?}");
    });
}

#[test]
fn collect_user_rules_filters_trashed_entries() {
    App::test((), |mut app| async move {
        initialize_app(&mut app);
        ObjectStoreModel::handle(&app).update(&mut app, |model, _| {
            for fact in [
                make_rule(1, Some("alive"), "live content", false),
                make_rule(2, Some("dead"), "should not appear", true),
            ] {
                model.add_object(fact.id, fact);
            }
        });

        let rules = app.read(|app| collect_user_rules(ObjectStoreModel::as_ref(app)));
        assert_eq!(rules.len(), 1, "trashed entries should be filtered out: {rules:?}");
        assert_eq!(rules[0].0.as_deref(), Some("alive"));
        assert_eq!(rules[0].1, "live content");
    });
}

#[test]
fn collect_user_rules_sorts_deterministically() {
    // Even with a shuffled insertion order and non-deterministic HashMap iteration
    // order, collect_user_rules must still produce a stable (name, content)
    // lexicographic output — this is a prerequisite for prompt cache hits.
    App::test((), |mut app| async move {
        initialize_app(&mut app);
        ObjectStoreModel::handle(&app).update(&mut app, |model, _| {
            // Deliberately inserted in reverse order
            for fact in [
                make_rule(10, Some("zebra"), "z content", false),
                make_rule(11, Some("alpha"), "a content", false),
                make_rule(12, Some("mango"), "m content", false),
            ] {
                model.add_object(fact.id, fact);
            }
        });

        let rules = app.read(|app| collect_user_rules(ObjectStoreModel::as_ref(app)));
        let names: Vec<_> = rules.iter().filter_map(|(n, _)| n.clone()).collect();
        assert_eq!(
            names,
            vec!["alpha", "mango", "zebra"],
            "should be sorted lexicographically by name: {names:?}"
        );
    });
}

#[test]
fn collect_user_rules_handles_unnamed_rules() {
    // None < Some holds under Rust's PartialOrd, so entries without a name should sort first.
    App::test((), |mut app| async move {
        initialize_app(&mut app);
        ObjectStoreModel::handle(&app).update(&mut app, |model, _| {
            for fact in [
                make_rule(1, Some("named"), "named content", false),
                make_rule(2, None, "unnamed content", false),
            ] {
                model.add_object(fact.id, fact);
            }
        });

        let rules = app.read(|app| collect_user_rules(ObjectStoreModel::as_ref(app)));
        assert_eq!(rules.len(), 2);
        assert_eq!(rules[0].0, None, "entries without a name should sort first: {rules:?}");
        assert_eq!(rules[0].1, "unnamed content");
        assert_eq!(rules[1].0.as_deref(), Some("named"));
    });
}

// --- `/copy-debugging-id` payload gating (upstream b4070d6a9) ---

/// On dogfood channels the clipboard artifact is the deeplink, which the running app can
/// open. `debug_link()` reads the process-wide channel for its URL scheme, so the expected
/// value is derived from the same source rather than hardcoded.
#[test]
fn debugging_payload_is_link_on_dogfood_channels() {
    use warp_core::channel::Channel;

    let token = ServerConversationToken::new("conversation-token".to_owned());
    let request_id = ServerOutputId::new("request-id".to_owned());
    let expected_link = token.debug_link();

    for channel in [Channel::Dev, Channel::Local] {
        assert_eq!(
            token.debugging_payload_for_channel(None, channel),
            expected_link
        );
        assert_eq!(
            token.debugging_payload_for_channel(Some(&request_id), channel),
            format!("{expected_link}?request=request-id")
        );
    }
}

/// On every user-facing channel the artifact is a plain id blob instead: that is what a
/// user can paste into a Phosphor issue, where a deeplink would be meaningless.
#[test]
fn debugging_payload_is_id_on_non_dogfood_channels() {
    use warp_core::channel::Channel;

    let token = ServerConversationToken::new("conversation-token".to_owned());
    let request_id = ServerOutputId::new("request-id".to_owned());

    for channel in [
        Channel::Stable,
        Channel::Preview,
        Channel::Integration,
        Channel::Oss,
    ] {
        assert_eq!(
            token.debugging_payload_for_channel(None, channel),
            "{\"conversation_id\":\"conversation-token\"}"
        );
        assert_eq!(
            token.debugging_payload_for_channel(Some(&request_id), channel),
            "{\"request_id\":\"request-id\",\"conversation_id\":\"conversation-token\"}"
        );
    }
}
