-- Zap does not maintain a down migration here: LSP and persisted workspace
-- history have been permanently removed, so there is no reasonable rollback
-- target. This empty file is kept to satisfy the diesel migration directory convention.
