//! Round-trip and mapping tests for the diff-state proto conversions.

use std::path::PathBuf;
use std::sync::Arc;

use super::*;
use crate::code_review::diff_size_limits::{DiffSize, MAX_DIFF_SIZE};
use crate::code_review::diff_state::{
    DiffHunk, DiffLine, DiffLineType, DiffMetadata, DiffMetadataAgainstBase, DiffMode, DiffState,
    DiffStats, FileDiff, FileDiffAndContent, FileStatusInfo, GitDiffData, GitDiffWithBaseContent,
    GitFileStatus,
};
use crate::util::git::{Commit, FileChangeEntry, PrInfo};

fn sample_line(line_type: DiffLineType) -> DiffLine {
    DiffLine {
        line_type,
        old_line_number: Some(3),
        new_line_number: None,
        text: "let x = 1;".to_string(),
        no_trailing_newline: true,
    }
}

fn sample_hunk() -> DiffHunk {
    DiffHunk {
        old_start_line: 10,
        old_line_count: 2,
        new_start_line: 10,
        new_line_count: 3,
        lines: vec![
            sample_line(DiffLineType::Context),
            sample_line(DiffLineType::Add),
            sample_line(DiffLineType::Delete),
        ],
        unified_diff_start: 100,
        unified_diff_end: 140,
    }
}

fn sample_file_diff() -> FileDiff {
    FileDiff {
        file_path: PathBuf::from("src/main.rs"),
        status: GitFileStatus::Renamed {
            old_path: "src/old.rs".to_string(),
        },
        hunks: Arc::new(vec![sample_hunk()]),
        is_binary: false,
        is_autogenerated: false,
        max_line_number: 42,
        has_hidden_bidi_chars: false,
        size: DiffSize::Normal,
    }
}

#[test]
fn diff_line_round_trips_all_types() {
    for lt in [
        DiffLineType::Context,
        DiffLineType::Add,
        DiffLineType::Delete,
        DiffLineType::HunkHeader,
    ] {
        let original = sample_line(lt);
        let back = proto_to_diff_line(&diff_line_to_proto(&original));
        assert_eq!(original, back);
    }
}

#[test]
fn diff_line_type_unspecified_falls_back_to_context() {
    // Wire value 0 (UNSPECIFIED) is never produced by us but must decode safely.
    assert_eq!(proto_to_diff_line_type(0), DiffLineType::Context);
}

#[test]
fn diff_hunk_round_trips() {
    let original = sample_hunk();
    let back = proto_to_diff_hunk(&diff_hunk_to_proto(&original));
    assert_eq!(original, back);
}

#[test]
fn git_file_status_round_trips_all_variants() {
    for status in [
        GitFileStatus::New,
        GitFileStatus::Modified,
        GitFileStatus::Deleted,
        GitFileStatus::Renamed {
            old_path: "a".to_string(),
        },
        GitFileStatus::Copied {
            old_path: "b".to_string(),
        },
        GitFileStatus::Untracked,
        GitFileStatus::Conflicted,
    ] {
        let back = proto_to_git_file_status(&git_file_status_to_proto(&status));
        assert_eq!(status, back);
    }
}

#[test]
fn git_file_status_missing_oneof_defaults_to_modified() {
    let empty = proto::GitFileStatus { status: None };
    assert_eq!(proto_to_git_file_status(&empty), GitFileStatus::Modified);
}

#[test]
fn diff_size_round_trips_and_maps_file_too_large() {
    for size in [DiffSize::Normal, DiffSize::Large, DiffSize::Unrenderable] {
        let back = proto_to_diff_size(diff_size_to_proto(&size) as i32);
        assert_eq!(size, back);
    }
    // The fork lacks the file-too-large distinction; it collapses to Unrenderable.
    assert_eq!(
        proto_to_diff_size(proto::DiffSize::UnrenderableFileTooLarge as i32),
        DiffSize::Unrenderable
    );
}

#[test]
fn file_diff_round_trips_with_base_content() {
    let original = sample_file_diff();
    let content = Some("base file content".to_string());
    let encoded = file_diff_to_proto(&original, content.clone());
    assert_eq!(encoded.content_at_base, content);
    let (back, decoded_content) = proto_to_file_diff(&encoded);
    assert_eq!(original, back);
    assert_eq!(decoded_content, content);
}

#[test]
fn git_diff_data_round_trips() {
    let original = GitDiffData {
        files: vec![sample_file_diff()],
        total_additions: 7,
        total_deletions: 4,
        files_changed: 1,
    };
    let back = proto_to_git_diff_data(&git_diff_data_to_proto(&original));
    assert_eq!(original, back);
}

#[test]
fn diff_mode_round_trips_all_variants() {
    for mode in [
        DiffMode::Head,
        DiffMode::MainBranch,
        DiffMode::OtherBranch("feature/x".to_string()),
    ] {
        let back = proto_to_diff_mode(&diff_mode_to_proto(&mode));
        assert_eq!(mode, back);
    }
}

#[test]
fn diff_state_maps_variants_and_folds_payload() {
    // Non-loaded variants carry no payload.
    match proto_to_diff_state(&diff_state_to_proto(&DiffState::NotInRepository), None) {
        DiffState::NotInRepository => {}
        _ => panic!("expected NotInRepository"),
    }
    match proto_to_diff_state(&diff_state_to_proto(&DiffState::Loading), None) {
        DiffState::Loading => {}
        _ => panic!("expected Loading"),
    }
    match proto_to_diff_state(
        &diff_state_to_proto(&DiffState::Error("boom".to_string())),
        None,
    ) {
        DiffState::Error(msg) => assert_eq!(msg, "boom"),
        _ => panic!("expected Error"),
    }

    // Loaded folds the separately-carried diffs payload back in.
    let diffs = GitDiffData {
        files: vec![sample_file_diff()],
        total_additions: 1,
        total_deletions: 0,
        files_changed: 1,
    };
    let proto_state = diff_state_to_proto(&DiffState::Loaded(diffs.clone()));
    match proto_to_diff_state(&proto_state, Some(diffs.clone())) {
        DiffState::Loaded(back) => assert_eq!(back, diffs),
        _ => panic!("expected Loaded"),
    }
}

#[test]
fn file_status_info_round_trips() {
    // Path must be absolute: `FileStatusInfo::try_from` (issue #326) now
    // rejects relative paths.
    let original = FileStatusInfo {
        path: PathBuf::from("/repo/src/lib.rs"),
        status: GitFileStatus::Deleted,
    };
    let back = FileStatusInfo::try_from(&file_status_info_to_proto(&original)).unwrap();
    assert_eq!(original.path, back.path);
    assert_eq!(original.status, back.status);
}

#[test]
fn file_change_entry_round_trips() {
    let original = FileChangeEntry {
        path: "src/x.rs".to_string(),
        additions: 12,
        deletions: 5,
    };
    let back = proto_to_file_change_entry(&file_change_entry_to_proto(&original));
    assert_eq!(original, back);
}

#[test]
fn commit_round_trips_forks_fields_and_encodes_empty_files() {
    let original = Commit {
        hash: "abc123".to_string(),
        subject: "fix: thing".to_string(),
        files_changed: 3,
        additions: 20,
        deletions: 8,
    };
    let encoded = commit_to_proto(&original);
    // The fork has no per-file list; it must encode empty (not fabricated).
    assert!(encoded.files.is_empty());
    let back = proto_to_commit(&encoded);
    assert_eq!(original, back);
}

#[test]
fn pr_info_round_trips() {
    let original = PrInfo {
        number: 42,
        url: "https://example.com/pr/42".to_string(),
        state: "MERGED".to_string(),
        draft: true,
        base_branch: "main".to_string(),
    };
    let encoded = pr_info_to_proto(&original);
    assert_eq!(encoded.state, "MERGED");
    assert!(encoded.draft);
    assert_eq!(encoded.base_branch, "main");
    let back = proto_to_pr_info(&encoded);
    assert_eq!(original, back);
}

fn sample_stats(files: usize) -> DiffStats {
    DiffStats {
        files_changed: files,
        total_additions: files * 10,
        total_deletions: files * 3,
    }
}

#[test]
fn diff_stats_round_trips() {
    let original = sample_stats(4);
    let back = proto_to_diff_stats(&diff_stats_to_proto(&original));
    assert_eq!(original, back);
}

#[test]
fn diff_metadata_against_base_round_trips_and_encodes_empty_files() {
    let original = DiffMetadataAgainstBase {
        aggregate_stats: sample_stats(2),
    };
    let encoded = diff_metadata_against_base_to_proto(&original);
    // The fork carries no per-file list here; it must encode empty.
    assert!(encoded.files.is_empty());
    let back = DiffMetadataAgainstBase::try_from(&encoded).unwrap();
    assert_eq!(original, back);
}

#[test]
fn diff_metadata_round_trips() {
    let original = DiffMetadata {
        main_branch_name: "main".to_string(),
        current_branch_name: "feature/x".to_string(),
        against_head: DiffMetadataAgainstBase {
            aggregate_stats: sample_stats(3),
        },
        against_base_branch: Some(DiffMetadataAgainstBase {
            aggregate_stats: sample_stats(5),
        }),
        has_head_commit: true,
        unpushed_commits: vec![Commit {
            hash: "deadbeef".to_string(),
            subject: "feat: y".to_string(),
            files_changed: 2,
            additions: 9,
            deletions: 1,
        }],
        upstream_ref: Some("origin/feature/x".to_string()),
        pr_info: Some(PrInfo {
            number: 7,
            url: "https://example.com/pr/7".to_string(),
            state: "OPEN".to_string(),
            draft: false,
            base_branch: "main".to_string(),
        }),
    };
    let back = DiffMetadata::try_from(&diff_metadata_to_proto(&original)).unwrap();
    assert_eq!(original, back);
}

#[test]
fn diff_metadata_default_round_trips() {
    let original = DiffMetadata::default();
    let back = DiffMetadata::try_from(&diff_metadata_to_proto(&original)).unwrap();
    assert_eq!(original, back);
}

#[test]
fn build_snapshot_loaded_carries_diffs_payload() {
    let diffs = GitDiffData {
        files: vec![sample_file_diff()],
        total_additions: 3,
        total_deletions: 1,
        files_changed: 1,
    };
    let snapshot = build_snapshot(
        "/repo".to_string(),
        &DiffMode::Head,
        &DiffState::Loaded(diffs.clone()),
        &DiffMetadata::default(),
    );
    assert_eq!(snapshot.repo_path, "/repo");
    assert!(matches!(
        snapshot.state.as_ref().and_then(|s| s.state.as_ref()),
        Some(proto::diff_state::State::Loaded(_))
    ));
    // The diff payload rides separately in `diffs`, not inside the state tag.
    let decoded = proto_to_git_diff_data(snapshot.diffs.as_ref().expect("loaded → diffs present"));
    assert_eq!(decoded, diffs);
}

#[test]
fn build_snapshot_not_in_repository_omits_diffs() {
    let snapshot = build_snapshot(
        "/repo".to_string(),
        &DiffMode::Head,
        &DiffState::NotInRepository,
        &DiffMetadata::default(),
    );
    assert!(snapshot.diffs.is_none());
    assert!(matches!(
        snapshot.state.as_ref().and_then(|s| s.state.as_ref()),
        Some(proto::diff_state::State::NotInRepository(_))
    ));
}

#[test]
fn error_response_wraps_message() {
    let resp = error_response("nope".to_string());
    match resp.result {
        Some(proto::get_diff_state_response::Result::Error(e)) => assert_eq!(e.message, "nope"),
        _ => panic!("expected error result"),
    }
}

#[test]
fn git_diff_with_base_content_preserves_per_file_content() {
    let proto_data = proto::GitDiffData {
        files: vec![file_diff_to_proto(
            &sample_file_diff(),
            Some("base content".to_string()),
        )],
        total_additions: 5,
        total_deletions: 2,
        files_changed: 1,
    };
    let decoded = proto_to_git_diff_with_base_content(&proto_data);
    assert_eq!(decoded.files.len(), 1);
    // The proto `content_at_base` lands on `FileDiffAndContent::content_at_head`.
    assert_eq!(
        decoded.files[0].content_at_head.as_deref(),
        Some("base content")
    );
    assert_eq!(decoded.files[0].file_diff, sample_file_diff());
    assert_eq!(decoded.files_changed, 1);
}

#[test]
fn decode_snapshot_folds_loaded_diffs_and_metadata() {
    let diffs = GitDiffData {
        files: vec![sample_file_diff()],
        total_additions: 3,
        total_deletions: 1,
        files_changed: 1,
    };
    let mut metadata = DiffMetadata::default();
    metadata.current_branch_name = "feature/x".to_string();
    let snapshot = build_snapshot(
        "/repo".to_string(),
        &DiffMode::Head,
        &DiffState::Loaded(diffs.clone()),
        &metadata,
    );

    let decoded = decode_snapshot(&snapshot).unwrap();
    match decoded.state {
        DiffState::Loaded(data) => assert_eq!(data, diffs),
        _ => panic!("expected Loaded"),
    }
    assert_eq!(decoded.metadata.current_branch_name, "feature/x");
    // The base-content payload is available separately for NewDiffsComputed.
    assert!(decoded.diffs.is_some());
    assert_eq!(decoded.diffs.unwrap().files_changed, 1);
}

#[test]
fn decode_snapshot_not_in_repository_has_no_diffs() {
    let snapshot = build_snapshot(
        "/repo".to_string(),
        &DiffMode::Head,
        &DiffState::NotInRepository,
        &DiffMetadata::default(),
    );
    let decoded = decode_snapshot(&snapshot).unwrap();
    assert!(matches!(decoded.state, DiffState::NotInRepository));
    assert!(decoded.diffs.is_none());
}

#[test]
fn snapshot_from_parts_picks_state_by_inputs() {
    let gdd = GitDiffData {
        files: vec![sample_file_diff()],
        total_additions: 1,
        total_deletions: 0,
        files_changed: 1,
    };
    // metadata Some + diff Some → Loaded
    let loaded = snapshot_from_parts(
        "/r".to_string(),
        &DiffMode::Head,
        Some(DiffMetadata::default()),
        Some(gdd.clone()),
    );
    assert!(matches!(
        loaded.state.and_then(|s| s.state),
        Some(proto::diff_state::State::Loaded(_))
    ));
    assert!(loaded.diffs.is_some());

    // metadata Some + diff None → Error
    let err = snapshot_from_parts(
        "/r".to_string(),
        &DiffMode::Head,
        Some(DiffMetadata::default()),
        None,
    );
    assert!(matches!(
        err.state.and_then(|s| s.state),
        Some(proto::diff_state::State::Error(_))
    ));

    // metadata None → NotInRepository
    let nir = snapshot_from_parts("/r".to_string(), &DiffMode::Head, None, Some(gdd));
    assert!(matches!(
        nir.state.and_then(|s| s.state),
        Some(proto::diff_state::State::NotInRepository(_))
    ));
}

#[test]
fn snapshot_from_parts_with_base_content_carries_content_at_base() {
    // Issue #388 item 4: unlike `snapshot_from_parts` (which only ever sees the
    // content-less `GitDiffData`), the daemon's `GetDiffState` reply and live-push
    // paths call this with the richer `GitDiffWithBaseContent` they already computed,
    // and `content_at_base` must actually reach the wire instead of being dropped.
    let diffs = GitDiffWithBaseContent {
        files: vec![FileDiffAndContent {
            file_diff: sample_file_diff(),
            content_at_head: Some("fn main() {}".to_string()),
        }],
        total_additions: 3,
        total_deletions: 1,
        files_changed: 1,
    };
    let snapshot = snapshot_from_parts_with_base_content(
        "/repo".to_string(),
        &DiffMode::Head,
        Some(DiffMetadata::default()),
        Some(diffs),
    );

    assert!(matches!(
        snapshot.state.as_ref().and_then(|s| s.state.as_ref()),
        Some(proto::diff_state::State::Loaded(_))
    ));
    let diffs_proto = snapshot.diffs.expect("loaded → diffs present");
    assert_eq!(diffs_proto.files.len(), 1);
    assert_eq!(
        diffs_proto.files[0].content_at_base.as_deref(),
        Some("fn main() {}"),
        "content_at_base must survive from GitDiffWithBaseContent onto the wire"
    );

    // metadata Some + diff None → Error, matching `snapshot_from_parts`.
    let err = snapshot_from_parts_with_base_content(
        "/repo".to_string(),
        &DiffMode::Head,
        Some(DiffMetadata::default()),
        None,
    );
    assert!(matches!(
        err.state.and_then(|s| s.state),
        Some(proto::diff_state::State::Error(_))
    ));
    assert!(err.diffs.is_none());

    // metadata None → NotInRepository, regardless of diff_data.
    let nir = snapshot_from_parts_with_base_content("/repo".to_string(), &DiffMode::Head, None, None);
    assert!(matches!(
        nir.state.and_then(|s| s.state),
        Some(proto::diff_state::State::NotInRepository(_))
    ));
}

#[test]
fn decode_file_delta_decodes_path_diff_and_metadata() {
    let mut metadata = DiffMetadata::default();
    metadata.main_branch_name = "main".to_string();
    let delta = proto::DiffStateFileDelta {
        repo_path: "/repo".to_string(),
        mode: Some(diff_mode_to_proto(&DiffMode::Head)),
        file_path: "src/x.rs".to_string(),
        diff: Some(file_diff_to_proto(
            &sample_file_diff(),
            Some("c".to_string()),
        )),
        metadata: Some(diff_metadata_to_proto(&metadata)),
    };
    let decoded = decode_file_delta(&delta).unwrap();
    assert_eq!(decoded.file_path, "src/x.rs");
    let file = decoded.diff.expect("delta carried a diff");
    assert_eq!(file.content_at_head.as_deref(), Some("c"));
    assert_eq!(file.file_diff, sample_file_diff());
    assert_eq!(
        decoded.metadata.expect("delta carried metadata").main_branch_name,
        "main"
    );
}

// ── Ported from the pinned oracle (02b53fcd8) ───────────────────────
// The pin's `file_diff_to_proto` gates base content on a size budget and
// drops it entirely for binary files; the fork's version originally shipped
// without that gating (dead code, pre-consumer). Ported alongside a matching
// fix in `file_diff_to_proto`. See diff_state_proto.rs for the gating logic.

#[test]
fn file_diff_to_proto_preserves_repo_relative_path() {
    let file_diff = sample_file_diff();

    let proto_diff = file_diff_to_proto(&file_diff, None);

    assert_eq!(proto_diff.file_path, "src/main.rs");
}

#[test]
fn build_diff_state_snapshot_preserves_repo_relative_file_paths() {
    // The pin's `build_diff_state_snapshot` takes `diffs` separately from
    // `state`; the fork's `build_snapshot` folds the diff payload into
    // `DiffState::Loaded` instead (see `diff_state_to_proto`'s doc comment).
    // Adapted to the fork's real signature; same assertion — the snapshot's
    // file paths stay repo-relative, not rewritten to an absolute path.
    let diffs = GitDiffData {
        files: vec![sample_file_diff()],
        total_additions: 0,
        total_deletions: 0,
        files_changed: 1,
    };

    let snapshot = build_snapshot(
        "/repo".to_string(),
        &DiffMode::Head,
        &DiffState::Loaded(diffs),
        &DiffMetadata::default(),
    );

    assert_eq!(
        snapshot
            .diffs
            .expect("snapshot should include diffs")
            .files
            .first()
            .expect("snapshot should include a file")
            .file_path,
        "src/main.rs"
    );
}

#[test]
fn build_diff_state_file_delta_preserves_repo_relative_file_path() {
    let delta = build_diff_state_file_delta("/repo", &DiffMode::Head, "src/main.rs", None, None);

    assert_eq!(delta.file_path, "src/main.rs");
}

#[test]
fn file_diff_to_proto_drops_binary_content() {
    let mut file_diff = sample_file_diff();
    file_diff.is_binary = true;

    let proto_diff = file_diff_to_proto(&file_diff, Some("binary blob content".to_string()));

    assert!(proto_diff.is_binary);
    assert_eq!(proto_diff.content_at_base, None);
    // Size is untouched for binary files; the client renders the binary
    // placeholder via `is_binary`, not via size.
    assert_eq!(proto_diff.size, proto::DiffSize::Normal as i32);
}

#[test]
fn file_diff_to_proto_withholds_oversized_content() {
    let file_diff = sample_file_diff();
    let oversized = "a".repeat(MAX_DIFF_SIZE + 1);

    let proto_diff = file_diff_to_proto(&file_diff, Some(oversized));

    assert_eq!(proto_diff.content_at_base, None);
    assert_eq!(
        proto_diff.size,
        proto::DiffSize::UnrenderableFileTooLarge as i32
    );
}

#[test]
fn file_diff_to_proto_preserves_content_within_budget() {
    let file_diff = sample_file_diff();

    let proto_diff = file_diff_to_proto(&file_diff, Some("small base content".to_string()));

    assert_eq!(
        proto_diff.content_at_base.as_deref(),
        Some("small base content")
    );
    assert_eq!(proto_diff.size, proto::DiffSize::Normal as i32);
}

#[test]
fn file_diff_to_proto_preserves_content_at_budget_boundary() {
    let file_diff = sample_file_diff();
    // The gate uses a strict `>` comparison, so base content of exactly
    // MAX_DIFF_SIZE is the largest blob still sent: content is preserved and
    // the size stays Normal rather than flipping to UnrenderableFileTooLarge.
    let at_budget = "a".repeat(MAX_DIFF_SIZE);

    let proto_diff = file_diff_to_proto(&file_diff, Some(at_budget.clone()));

    assert_eq!(
        proto_diff.content_at_base.as_deref(),
        Some(at_budget.as_str())
    );
    assert_eq!(proto_diff.size, proto::DiffSize::Normal as i32);
}

// ── Ported from the pinned oracle (02b53fcd8) — issue #326 ─────────────
// The pin's `FileStatusInfo`/`DiffMetadataAgainstBase`/`DiffMetadata` decode
// via `TryFrom`, rejecting malformed wire data instead of silently defaulting.
// Adapted to the fork's real types: the pin parses `path`/`old_path` as
// `StandardizedPath`; the fork's `FileStatusInfo::path` stays a plain
// `PathBuf` (see the `TryFrom<&proto::FileStatusInfo>` doc comment above for
// why), so `file_status_info_valid_absolute_path` asserts a `PathBuf` rather
// than a `StandardizedPath`. Same rejection assertions otherwise.

#[test]
fn file_status_info_valid_absolute_path() {
    let proto_info = proto::FileStatusInfo {
        path: "/repo/src/main.rs".into(),
        status: Some(proto::GitFileStatus {
            status: Some(proto::git_file_status::Status::NewFile(
                proto::GitFileStatusNew {},
            )),
        }),
    };

    let info = FileStatusInfo::try_from(&proto_info).unwrap();
    assert_eq!(info.path, PathBuf::from("/repo/src/main.rs"));
    assert_eq!(info.status, GitFileStatus::New);
}

#[test]
fn file_status_info_missing_status_is_error() {
    let proto_info = proto::FileStatusInfo {
        path: "/repo/file.rs".into(),
        status: None,
    };

    assert!(FileStatusInfo::try_from(&proto_info).is_err());
}

#[test]
fn file_status_info_missing_status_variant_is_error() {
    let proto_info = proto::FileStatusInfo {
        path: "/repo/file.rs".into(),
        status: Some(proto::GitFileStatus { status: None }),
    };

    assert!(FileStatusInfo::try_from(&proto_info).is_err());
}

#[test]
fn file_status_info_validates_renamed_old_path() {
    let proto_info = proto::FileStatusInfo {
        path: "/repo/new_name.rs".into(),
        status: Some(proto::GitFileStatus {
            status: Some(proto::git_file_status::Status::Renamed(
                proto::GitFileStatusRenamed {
                    old_path: "relative/old.rs".into(),
                },
            )),
        }),
    };

    // old_path is relative — should fail validation.
    assert!(FileStatusInfo::try_from(&proto_info).is_err());
}

#[test]
fn diff_metadata_requires_against_head() {
    let metadata = proto::DiffMetadata {
        main_branch_name: "main".into(),
        current_branch_name: "feature".into(),
        against_head: None,
        against_base_branch: None,
        has_head_commit: true,
        unpushed_commits: vec![],
        upstream_ref: None,
        pr_info: None,
    };

    assert!(DiffMetadata::try_from(&metadata).is_err());
}

#[test]
fn diff_metadata_against_base_requires_stats() {
    let against_base = proto::DiffMetadataAgainstBase {
        aggregate_stats: None,
        files: vec![],
    };

    assert!(DiffMetadataAgainstBase::try_from(&against_base).is_err());
}

// ── Ported from the pinned oracle (02b53fcd8),
// `app/src/remote_server/diff_state_proto_tests.rs::pr_info_round_trips_through_proto` ──
//
// The PR banner over SSH (number, state, draft flag, base branch) is rendered
// straight from what crosses this boundary, so a dropped field shows up as a
// wrong or missing banner rather than an error. Nothing else pins it.
//
// Adaptation: the pin converts through `From<&PrInfo> for proto::PrInfo` /
// `From<&proto::PrInfo> for PrInfo`; this fork uses the free functions
// `pr_info_to_proto` / `proto_to_pr_info` in the module under test.
#[test]
fn pr_info_round_trips_through_proto() {
    let pr_info = PrInfo {
        number: 42,
        url: "https://example.com/owner/repo/pull/42".into(),
        state: "OPEN".into(),
        draft: true,
        base_branch: "develop".into(),
    };

    let proto_info = pr_info_to_proto(&pr_info);
    let decoded = proto_to_pr_info(&proto_info);

    assert_eq!(decoded, pr_info);
}
