//! Round-trip and mapping tests for the diff-state proto conversions.

use std::path::PathBuf;
use std::sync::Arc;

use super::*;
use crate::code_review::diff_size_limits::DiffSize;
use crate::code_review::diff_state::{
    DiffHunk, DiffLine, DiffLineType, DiffMode, DiffState, FileDiff, FileStatusInfo, GitDiffData,
    GitFileStatus,
};
use crate::util::git::{Commit, FileChangeEntry, PrInfo};

fn sample_line(line_type: DiffLineType) -> DiffLine {
    DiffLine {
        line_type,
        old_line_number: Some(3),
        new_line_number: None,
        text: "let x = 1;".to_string(),
        no_trailing_newline: true,
    }
}

fn sample_hunk() -> DiffHunk {
    DiffHunk {
        old_start_line: 10,
        old_line_count: 2,
        new_start_line: 10,
        new_line_count: 3,
        lines: vec![
            sample_line(DiffLineType::Context),
            sample_line(DiffLineType::Add),
            sample_line(DiffLineType::Delete),
        ],
        unified_diff_start: 100,
        unified_diff_end: 140,
    }
}

fn sample_file_diff() -> FileDiff {
    FileDiff {
        file_path: PathBuf::from("src/main.rs"),
        status: GitFileStatus::Renamed {
            old_path: "src/old.rs".to_string(),
        },
        hunks: Arc::new(vec![sample_hunk()]),
        is_binary: false,
        is_autogenerated: false,
        max_line_number: 42,
        has_hidden_bidi_chars: false,
        size: DiffSize::Normal,
    }
}

#[test]
fn diff_line_round_trips_all_types() {
    for lt in [
        DiffLineType::Context,
        DiffLineType::Add,
        DiffLineType::Delete,
        DiffLineType::HunkHeader,
    ] {
        let original = sample_line(lt);
        let back = proto_to_diff_line(&diff_line_to_proto(&original));
        assert_eq!(original, back);
    }
}

#[test]
fn diff_line_type_unspecified_falls_back_to_context() {
    // Wire value 0 (UNSPECIFIED) is never produced by us but must decode safely.
    assert_eq!(proto_to_diff_line_type(0), DiffLineType::Context);
}

#[test]
fn diff_hunk_round_trips() {
    let original = sample_hunk();
    let back = proto_to_diff_hunk(&diff_hunk_to_proto(&original));
    assert_eq!(original, back);
}

#[test]
fn git_file_status_round_trips_all_variants() {
    for status in [
        GitFileStatus::New,
        GitFileStatus::Modified,
        GitFileStatus::Deleted,
        GitFileStatus::Renamed {
            old_path: "a".to_string(),
        },
        GitFileStatus::Copied {
            old_path: "b".to_string(),
        },
        GitFileStatus::Untracked,
        GitFileStatus::Conflicted,
    ] {
        let back = proto_to_git_file_status(&git_file_status_to_proto(&status));
        assert_eq!(status, back);
    }
}

#[test]
fn git_file_status_missing_oneof_defaults_to_modified() {
    let empty = proto::GitFileStatus { status: None };
    assert_eq!(proto_to_git_file_status(&empty), GitFileStatus::Modified);
}

#[test]
fn diff_size_round_trips_and_maps_file_too_large() {
    for size in [DiffSize::Normal, DiffSize::Large, DiffSize::Unrenderable] {
        let back = proto_to_diff_size(diff_size_to_proto(&size) as i32);
        assert_eq!(size, back);
    }
    // The fork lacks the file-too-large distinction; it collapses to Unrenderable.
    assert_eq!(
        proto_to_diff_size(proto::DiffSize::UnrenderableFileTooLarge as i32),
        DiffSize::Unrenderable
    );
}

#[test]
fn file_diff_round_trips_with_base_content() {
    let original = sample_file_diff();
    let content = Some("base file content".to_string());
    let encoded = file_diff_to_proto(&original, content.clone());
    assert_eq!(encoded.content_at_base, content);
    let (back, decoded_content) = proto_to_file_diff(&encoded);
    assert_eq!(original, back);
    assert_eq!(decoded_content, content);
}

#[test]
fn git_diff_data_round_trips() {
    let original = GitDiffData {
        files: vec![sample_file_diff()],
        total_additions: 7,
        total_deletions: 4,
        files_changed: 1,
    };
    let back = proto_to_git_diff_data(&git_diff_data_to_proto(&original));
    assert_eq!(original, back);
}

#[test]
fn diff_mode_round_trips_all_variants() {
    for mode in [
        DiffMode::Head,
        DiffMode::MainBranch,
        DiffMode::OtherBranch("feature/x".to_string()),
    ] {
        let back = proto_to_diff_mode(&diff_mode_to_proto(&mode));
        assert_eq!(mode, back);
    }
}

#[test]
fn diff_state_maps_variants_and_folds_payload() {
    // Non-loaded variants carry no payload.
    match proto_to_diff_state(&diff_state_to_proto(&DiffState::NotInRepository), None) {
        DiffState::NotInRepository => {}
        _ => panic!("expected NotInRepository"),
    }
    match proto_to_diff_state(&diff_state_to_proto(&DiffState::Loading), None) {
        DiffState::Loading => {}
        _ => panic!("expected Loading"),
    }
    match proto_to_diff_state(
        &diff_state_to_proto(&DiffState::Error("boom".to_string())),
        None,
    ) {
        DiffState::Error(msg) => assert_eq!(msg, "boom"),
        _ => panic!("expected Error"),
    }

    // Loaded folds the separately-carried diffs payload back in.
    let diffs = GitDiffData {
        files: vec![sample_file_diff()],
        total_additions: 1,
        total_deletions: 0,
        files_changed: 1,
    };
    let proto_state = diff_state_to_proto(&DiffState::Loaded(diffs.clone()));
    match proto_to_diff_state(&proto_state, Some(diffs.clone())) {
        DiffState::Loaded(back) => assert_eq!(back, diffs),
        _ => panic!("expected Loaded"),
    }
}

#[test]
fn file_status_info_round_trips() {
    let original = FileStatusInfo {
        path: PathBuf::from("src/lib.rs"),
        status: GitFileStatus::Deleted,
    };
    let back = proto_to_file_status_info(&file_status_info_to_proto(&original));
    assert_eq!(original.path, back.path);
    assert_eq!(original.status, back.status);
}

#[test]
fn file_change_entry_round_trips() {
    let original = FileChangeEntry {
        path: "src/x.rs".to_string(),
        additions: 12,
        deletions: 5,
    };
    let back = proto_to_file_change_entry(&file_change_entry_to_proto(&original));
    assert_eq!(original, back);
}

#[test]
fn commit_round_trips_forks_fields_and_encodes_empty_files() {
    let original = Commit {
        hash: "abc123".to_string(),
        subject: "fix: thing".to_string(),
        files_changed: 3,
        additions: 20,
        deletions: 8,
    };
    let encoded = commit_to_proto(&original);
    // The fork has no per-file list; it must encode empty (not fabricated).
    assert!(encoded.files.is_empty());
    let back = proto_to_commit(&encoded);
    assert_eq!(original, back);
}

#[test]
fn pr_info_round_trips_forks_fields_and_defaults_extras() {
    let original = PrInfo {
        number: 42,
        url: "https://example.com/pr/42".to_string(),
    };
    let encoded = pr_info_to_proto(&original);
    assert_eq!(encoded.state, "");
    assert!(!encoded.draft);
    assert_eq!(encoded.base_branch, "");
    let back = proto_to_pr_info(&encoded);
    assert_eq!(original, back);
}
